version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flatworthy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - osdata:/usr/share/opensearch/data

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-01Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  createbucket:
    image: minio/mc:RELEASE.2025-01-20T16-47-26Z
    depends_on:
      - minio
    entrypoint: >-
      /bin/sh -c "
      sleep 2 &&
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb -p local/flatworthy-media || true &&
      mc anonymous set public local/flatworthy-media
      "

volumes:
  pgdata: {}
  redisdata: {}
  osdata: {}
  miniodata: {}